apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-blue
  minReadySeconds: 10
  strategy: 
    matchLabels:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: hello-blue
        version: "1.3"
        colour: "blue" 
    spec:
      containers:
      - name: hello-blue
        image: neggs/helloworld:latest 
        ports: 
        - containerPort: 8080
